name: Build Jacoco Report and Badge
run-name: ${{ github.actor }} 
on: 
  push:
    branches:
      - master
      
jobs:
  # Build Codes with Gradle
  build:
    name: Build Source Codes to Executable Jar
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Codes
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK and Download Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      # Run Test and Generate Test Report
      - name: Run Tests and Generate Test Report
        run: ./gradlew test && ./gradlew jacocoTestReport
      
      # Get Test Report Location
      - name: Get Test Report Location
        run: find ./build -type f -name "*csv"
        
      # https://github.com/marketplace/actions/jacoco-badge-generator       
      - name: Generate JaCoCo Badge
        id: jacoco 
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'TheMaos'
            git config --global user.email 'D3vYuan@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi