name: Deploy to AWS Elasticbean Stalk
run-name: ${{ github.actor }} 
on: 
  push:
    branches:
      - main
jobs:
  # Run Test and Build Jar
  build:
    name: Build Source Codes to Executable Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
      - name: Setup JDK
      - name: Build with Gradle
      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name, default is artifact
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/rest-service-0.0.1-SNAPSHOT.jar
  # Deploy
  deploy:
    name: Deploy to AWS Elasticbeanstalk
    # Depend on result of build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: artifact
      - name: Deploy to AWS Elasticbeanstalk
      
