name: Deploy to AWS Elasticbean Stalk
run-name: ${{ github.actor }} 
on: 
  push:
    branches:
      - main
jobs:
  # Build Codes with Gradle
  build:
    name: Build Source Codes to Executable Jar
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Codes
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk#caching-packages-dependencies
      - name: Setup JDK and Download Dependencies
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          cache: 'gradle'

      # Build Source Codes
      - run: ./gradlew build --no-daemon

      # Get Executable Jar Location
      - run: find . -type f -name "*jar"

      # Upload Executable Jar
      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name, default is artifact
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: build/**/rest-service-0.0.1-SNAPSHOT.jar
          # 'warn' or 'ignore' are also available, defaults to `warn`
          if-no-files-found: error
  # Deploy Executable Jar to AWS Elasticbeanstalk
  # deploy:
  #   name: Deploy to AWS Elasticbeanstalk
  #   # Depend on result of build
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v2.1.1
  #       with:
  #         # Artifact name
  #         name: artifact
  #     - name: Deploy to AWS Elasticbeanstalk
      
